# Dockerfile pro testování Ansible playbooku
FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y sudo openssh-server python3 python3-pip && \
    useradd -m tester && echo 'tester:heslo123' | chpasswd && \
    usermod -aG sudo tester && \
    mkdir /var/run/sshd

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
